### ISSUE TITLE
Duplicate meals in day editor are removed as a pair

### ISSUE THREAD

**Issue by nickslick03** [nickslick03/messiah-meal-planner#25]
![mmp_issue_1](https://github.com/nickslick03/messiah-meal-planner/assets/91232026/e2cca5c9-13c0-4cdd-80b2-146db7d456f3)

As the GIF shows, when a meal is added as a duplicate at least twice to the same day, when that meal is removed it removes the duplicate as well.

**Comment by cdrice26** [comment]
Ah good catch. I assigned IDs when adding to the meal queue to prevent this issue in the meal queue, but I forgot to reassign them when adding to the day editors. I pushed a fix to the state-management branch and created pull request #26 to bring this patch into development. It says there's a conflict, but it's just two different imports. All we need to do is when we are ready to merge, use the web editor to delete the diff lines and keep both imports.
