### ISSUE TITLE
Need to add discount for A La Carte/Commuter Meal Plans

### ISSUE THREAD

**Issue by cdrice26** [nickslick03/messiah-meal-planner#62]
I saw a poster in Lottie today that the A La Carte and Commuter meal plans were merging into a new set of meal plans, all with a 10% discount at all locations. To fix this, we can abstract the switch I'm using for the all/custom only toggle on the search bar into its own "Switch" component and then use that in the meal plan info to toggle between DD and ALC plans. I don't think there's any plans that don't have discounts (door price would only be if no meal plan or buying for a friend which is probably outside scope of project) so a switch between DD and ALC plans would probably be sufficient.

**Comment by nickslick03** [comment]
Yeah that def sounds like good change
